#ifndef G_ALL_H
# define G_ALL_H

#include "g_common.h"

#include "g_play.h"
#include "g_keyboard.h"
#include "midibase.h"
#include "g_midikey.h"
#include "g_midictrl.h"
#include "g_statetick.h"
#include "g_bridge.h"
#include "g_dc.h"
#include "g_wav.h"
#include "g_osc.h"
#include "g_mix.h"
#include "g_crossfade.h"
#include "g_abs.h"
#include "g_doppler.h"
#include "g_filter.h"
#include "g_delay.h"
#include "g_scope.h"
#include "g_gain.h"
#include "g_env.h"
#include "g_note.h"
#include "g_metro.h"
#include "g_punchpad.h"
#include "g_stepmatrix.h"
#include "g_drawenv.h"
#include "g_vector.h"
#include "g_select_in.h"
#include "g_samplehold.h"
#include "g_tracker.h"
#include "g_slew.h"
#include "g_clip.h"
#include "g_logistic.h"
#include "g_threshold.h"
#include "g_ahdsr.h"
#include "g_spec.h"
#include "g_drain.h"
#include "g_fft_filt.h"
#include "g_notegain.h"
#include "g_exp.h"
#include "g_log.h"
#include "g_divide.h"
#include "g_mult.h"
#include "g_sort.h"
#include "g_keyextr.h"
#include "g_gatetopulse.h"
#include "g_print.h"
#include "g_sign.h"
#include "g_plus.h"
#include "g_minus.h"
#include "g_min.h"
#include "g_max.h"
#include "g_floor.h"
#include "g_ceil.h"
#include "g_trunc.h"
#include "g_sin.h"
#include "g_mod.h"
#include "g_samplerate.h"
#include "g_execcmd.h"
#include "g_linear.h"
#include "g_lessthan.h"
#include "g_lessthanequal.h"
#include "g_integrate.h"
#include "g_changepulse.h"
#include "g_joystick.h"
#include "g_onoff.h"
#include "g_buffer.h"
#include "g_bitcrush.h"
#include "g_edelay.h"
//#include "g_altzeroctrl.h"


/*OBSOLETE*/
#include "g_adsr.h"
#include "g_octscale.h"

/*
  #include "g_waveshape.h"
*/

#include "g_help.h"

#endif
